version: '3.0'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - glitch-network 

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - glitch-network 

networks:
  glitch-network:
    driver: bridge
