# Generated by Django 5.0.4 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_activiteiten_id_alter_conceptopdracht_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activiteiten",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="conceptopdracht",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cursussen",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="domeinen",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hoofdopdrachten",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="niveaus",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="puntenuitdagingen",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
