# Generated by Django 5.0.4 on 2024-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_activiteiten_id_alter_conceptopdracht_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voortgangactiviteitenniveaus',
            name='voortgang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voortgangconceptopdrachten',
            name='voortgang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voortganghoofdopdrachten',
            name='voortgang',
            field=models.IntegerField(default=0),
        ),
    ]
