services:
  frontend:
    build:
      context: ./glitch/frontend
    command: npm start
    ports:
      - "8081:8081"

  backend:
    build:
      context: ./glitch/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - database:/backend/database
    ports:
      - "8000:8000"
volumes:
  database: