# Generated by Django 4.2.9 on 2024-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_teacher',
            field=models.BooleanField(default=0),
        ),
    ]
