# Generated by Django 4.2.9 on 2024-05-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_post'),
        ('authentication', '0002_gameuser_is_teacher'),
    ]

    operations = [
    ]
