# Generated by Django 5.0.4 on 2024-04-24 11:54

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursussen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64)),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('ingschr_cursus', models.ManyToManyField(to='game.cursussen', verbose_name='ingeschreven cursussen student')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64)),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cursussen')),
            ],
        ),
        migrations.CreateModel(
            name='HoofdOpdrachten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64)),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.modules')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptOpdracht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64)),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Activiteiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64)),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Niveaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.CharField(blank=True, max_length=640)),
                ('activiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.activiteiten')),
            ],
        ),
        migrations.CreateModel(
            name='PuntenUitdagingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benodige_punten', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.modules')),
            ],
        ),
        migrations.CreateModel(
            name='VoortgangActiviteitenNiveaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voortgang', models.IntegerField(default=0)),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.niveaus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='voortgang_activiteit_niveaus',
            field=models.ManyToManyField(blank=True, through='game.VoortgangActiviteitenNiveaus', to='game.niveaus'),
        ),
        migrations.CreateModel(
            name='VoortgangConceptOpdrachten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voortgang', models.BooleanField(default=False)),
                ('concept_opdracht', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.conceptopdracht')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='voortgang_concept_opdracht',
            field=models.ManyToManyField(blank=True, through='game.VoortgangConceptOpdrachten', to='game.conceptopdracht'),
        ),
        migrations.CreateModel(
            name='VoortgangHoofdOpdrachten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voortgang', models.BooleanField(default=False)),
                ('hoofd_opdracht', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.hoofdopdrachten')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='voortgang_hoofd_opdracht',
            field=models.ManyToManyField(blank=True, through='game.VoortgangHoofdOpdrachten', to='game.hoofdopdrachten'),
        ),
        migrations.CreateModel(
            name='VoortgangPuntenUitdaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voortgang', models.BooleanField(default=False)),
                ('punten_uitdaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.puntenuitdagingen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='voortgang_punten_uitdaging',
            field=models.ManyToManyField(blank=True, through='game.VoortgangPuntenUitdaging', to='game.puntenuitdagingen'),
        ),
    ]
