# Generated by Django 4.2.9 on 2024-05-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conceptopdracht',
            table='game_conceptopdracht',
        ),
    ]
