# Generated by Django 5.0.4 on 2024-05-21 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngschrCursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.cursussen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ingschr_cursus',
            field=models.ManyToManyField(blank=True, through='game.IngschrCursus', to='game.cursussen'),
        ),
    ]
