# Generated by Django 5.0.4 on 2024-06-05 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiteiten',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conceptopdracht',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursussen',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hoofdopdrachten',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='niveaus',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puntenuitdagingen',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voortgangactiviteitenniveaus',
            name='voortgang',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voortgangpuntenuitdaging',
            name='voortgang',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeacherCursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cursussen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cursus')},
            },
        ),
    ]
