# Generated by Django 5.0.4 on 2024-05-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingschrcursus',
            options={'managed': False},
        ),
    ]
