# Generated by Django 4.2.9 on 2024-05-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_conceptopdracht_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptopdracht',
            old_name='module',
            new_name='module_id',
        ),
    ]
