# Generated by Django 5.0.4 on 2024-05-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_ingschrcursus_alter_user_ingschr_cursus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ingschr_cursus',
            field=models.ManyToManyField(to='Cursussen', through='IngschrCursus', blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_activiteit_niveaus',
            field=models.ManyToManyField(to='game.niveaus', through='VoortgangHoofdOpdrachten', blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_concept_opdracht',
            field=models.ManyToManyField(to='game.conceptopdracht', through='VoortgangConceptOpdrachten', blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_hoofd_opdracht',
            field=models.ManyToManyField(to='HoofdOpdrachten', through='VoortgangHoofdOpdrachten', blank=True,),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_punten_uitdaging',
            field=models.ManyToManyField(to='PuntenUitdagingen', through='VoortgangPuntenUitdaging', blank=True,),
        ),
    ]
