# Generated by Django 5.0.4 on 2024-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_user_date_joined_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modules",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
    ]
