# Generated by Django 5.0.4 on 2024-06-05 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_activiteiten_id_alter_conceptopdracht_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domeinen",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=640,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naam", models.CharField(max_length=64)),
                ("beschrijving", models.CharField(blank=True, max_length=640)),
            ],
        ),
        migrations.AddField(
            model_name="cursussen",
            name="domein",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="game.domeinen",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="IngschrDomein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domein",
                    models.ForeignKey(
                        db_column="domeinen_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="game.domeinen",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="ingschr_domein",
            field=models.ManyToManyField(
                blank=True, through="game.IngschrDomein", to="game.domeinen"
            ),
        ),
    ]
