# Generated by Django 4.2.9 on 2024-05-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_module_conceptopdracht_module_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptopdracht',
            old_name='module_id',
            new_name='module',
        ),
    ]
