# Generated by Django 5.0.4 on 2024-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_ingschr_cursus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ingschr_cursus',
            field=models.ManyToManyField(blank=True, through='game.IngschrCursus', to='game.cursussen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_activiteit_niveaus',
            field=models.ManyToManyField(blank=True, through='game.VoortgangActiviteitenNiveaus', to='game.niveaus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_concept_opdracht',
            field=models.ManyToManyField(blank=True, through='game.VoortgangConceptOpdrachten', to='game.conceptopdracht'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_hoofd_opdracht',
            field=models.ManyToManyField(blank=True, through='game.VoortgangHoofdOpdrachten', to='game.hoofdopdrachten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voortgang_punten_uitdaging',
            field=models.ManyToManyField(blank=True, through='game.VoortgangPuntenUitdaging', to='game.puntenuitdagingen'),
        ),
    ]
