# Generated by Django 4.2.9 on 2024-05-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_ingschrcursus_options'),
        ('game', '0004_alter_user_ingschr_cursus_and_more'),
        ('game', '0004_rename_module_id_conceptopdracht_module'),
    ]

    operations = [
    ]
