# Generated by Django 5.0.4 on 2024-05-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_ingschrcursus_options'),
        ('game', '0003_alter_modules_id'),
        ('game', '0004_alter_user_ingschr_cursus_and_more'),
    ]

    operations = [
    ]
