# Generated by Django 5.0.4 on 2024-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20240529_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ingschr_cursus',
        ),
        migrations.AlterField(
            model_name='cursussen',
            name='id',
            field=models.CharField(editable=False, max_length=640, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='ingschrcursus',
            table='game_user_ingschr_cursus',
        ),
    ]
