# Generated by Django 5.0.4 on 2024-05-29 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_modules_id"),
        ("game", "0006_alter_user_date_joined_alter_user_email_and_more"),
    ]

    operations = []
