# Generated by Django 5.0.4 on 2024-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_merge_20240529_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activiteiten",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="conceptopdracht",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cursussen",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="hoofdopdrachten",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="niveaus",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="puntenuitdagingen",
            name="id",
            field=models.CharField(
                editable=False, max_length=640, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="voortgangactiviteitenniveaus",
            name="voortgang",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voortgangpuntenuitdaging",
            name="voortgang",
            field=models.IntegerField(default=0),
        ),
    ]
