# Generated by Django 5.0.4 on 2024-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_voortgangconceptopdrachten_ingeleverd_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='voortganghoofdopdrachten',
            name='ingeleverd_tekst',
            field=models.TextField(blank=True, null=True),
        ),
    ]
